# Generated by Django 3.1.6 on 2021-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0002_auto_20210219_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='presta_end',
            field=models.DateTimeField(default=None, verbose_name='end of presta'),
            preserve_default=False,
        ),
    ]
