# Generated by Django 3.1.6 on 2021-04-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0003_presta_presta_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presta',
            name='presta_end',
        ),
    ]
