# Generated by Django 3.1.6 on 2021-04-05 12:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0004_remove_presta_presta_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='presta_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end of presta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presta',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
