# Generated by Django 3.1.6 on 2021-04-17 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0007_auto_20210417_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presta',
            name='presta_date',
        ),
        migrations.AddField(
            model_name='presta',
            name='presta_date_n',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date of presta'),
        ),
    ]
