# Generated by Django 3.1.6 on 2021-04-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0008_auto_20210417_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presta',
            old_name='presta_date_n',
            new_name='presta_date',
        ),
    ]
