# Generated by Django 3.1.6 on 2021-04-17 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0009_auto_20210417_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='presta',
            name='presta_comments',
            field=models.TextField(default='', verbose_name='Commentaires Additionnels (Genres Musicales souhaitées, Lien de Playlist, etc.)'),
        ),
        migrations.AddField(
            model_name='presta',
            name='presta_place',
            field=models.CharField(default='', max_length=200, verbose_name='Lieu de Presta'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date de presta'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_end',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Heure de Fin'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_name',
            field=models.CharField(max_length=200, verbose_name='Nom de presta'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_respo',
            field=models.CharField(default='', max_length=200, verbose_name='Personne responsable'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_respo_mail',
            field=models.EmailField(default='', max_length=254, verbose_name='email respo'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_start',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Heure de Début'),
        ),
        migrations.AlterField(
            model_name='presta',
            name='presta_type',
            field=models.CharField(choices=[('FP', 'FP'), ('GS', 'Grande Soirée'), ('SC', 'Soirée Chill'), ('DM', 'Découverte Musicale'), ('AU', 'Autre')], max_length=3, verbose_name='Type de Presta désirée'),
        ),
    ]
