# Generated by Django 3.1.6 on 2021-06-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presta', '0011_auto_20210417_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presta',
            name='presta_comments',
            field=models.TextField(blank=True, default='', verbose_name='Commentaires Additionnels'),
        ),
    ]
